### ISSUE TITLE
create a Logo

### ISSUE THREAD

**Issue by Holger-Will** [node-enocean/node-enocean#27]
would be nice to have a logo for node-enocean. Help very welcome

**Comment by huwylphi** [comment]
something like this?

![node-enocean](https://cloud.githubusercontent.com/assets/3155226/25770947/647121b4-3243-11e7-929f-13df9a6abaf9.png)

**Comment by Holger-Will** [comment]
yeah, great! not sure we could use the enocean logo though... :-(

**Comment by huwylphi** [comment]
You are probably right. So I would have a new suggestion:

![node-enocean](https://user-images.githubusercontent.com/3155226/26884873-24e07c62-4ba1-11e7-817c-9589347c85ad.png)

(the original file is in svg)

**Comment by huwylphi** [comment]
What do you think?

**Comment by Holger-Will** [comment]
hi, sorry for not answering... im currently sitting in front of a pile of work...

i think it's much better. 
I still think a logo must be much simpler. 
- No Text if possible. 
- Just a very simple shape. 
- Colors are ok, but preferably a logo should work without color (monochrome). 
- The shape should fit in a square space...

Again thanks for your contribution. i appreciate your work!

**Comment by huwylphi** [comment]
Ok, you are right (again). I will try something according your recommendations.

**Comment by huwylphi** [comment]
I've made a new version without the dolphin (too complex). Instead of the doplhin I tried to represent the wireless notion.

![node-enocean-color1](https://user-images.githubusercontent.com/3155226/27455818-ece204b6-579e-11e7-917f-65653147d0c8.png)

![node-enocean-mono](https://user-images.githubusercontent.com/3155226/27455892-2ea65d84-579f-11e7-86ba-3e944f4d32d1.png)

**Comment by Holger-Will** [comment]
WOW! now we are getting somwhere. This is just great! thank you very much.

**Comment by huwylphi** [comment]
Thanks, I'm glad you like it. Maybe little enhancements are still needed (I stay open) but I send You the files in SVG format via pm, so you would have this version in "good" quality.

**Comment by Holger-Will** [comment]
using the logo now as a profile pic for node-enocean here on github...

**Comment by huwylphi** [comment]
Hi,
cool. I'm glad you can use it :)

Maybe you have to zoom the logo a little bit, because today it's shown cut on top and bottom.
![image](https://user-images.githubusercontent.com/3155226/28110799-bdb5e630-66f3-11e7-91ef-8677492d06c2.png)

What format and dimension are allowed from github? If you zoom the logo, you can do it in svg format (sent via pm) so you would not loose quality. I use [Vectr ](https://vectr.com/)as (free) svg editor.

**Comment by Holger-Will** [comment]
Yep did not manage to change the logo yet... will do soon...
I usally edit my SVGs by Hand... ;-)

**Comment by Holger-Will** [comment]
hey, i've managed to change the logo a bit. I looks fantastic! i'm also using it on the new node-enocean website including your color-schema... check it out: http://node.enocean.de
Thanks again for your contribution!

**Comment by Holger-Will** [comment]
closing, as the logo is just fantastic and is now used in several places
